### ISSUE TITLE
Hmodel_features files

### ISSUE THREAD

**Issue by shree970** [XinhaoLi74/Hierarchical-QSAR-Modeling#1]
Hi, very cool project and very convenient for property prediction. I would like to know for file Hierarchical_features.ipynb, block number 3. 

>Hfeature_path = '../data/Hmodel_features/'
>train_Hfeatures = Hfeature_collector(Hfeature_path)
>train_Hfeatures.shape 

outputs as
>"60 files found"
>(8221, 100)

I could not see any method in other codes to generate these 60 files. Although they are present for Bmodel_features.

**Comment by XinhaoLi74** [comment]
Hi, 
The `Hmodel_features` are the `out-of-fold predictions` of the base models. They are generated in `Base_models.ipynb`. 

For example: 
```
BCM_mf.to_csv(f'../data/Hmodel_features/{name}.csv')
```
I hope this is helpful. Please let me know if you have any further questions.
